"""empty message

Revision ID: f57873e1c499
Revises: 100c08b1fc26
Create Date: 2025-03-09 20:31:31.108091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f57873e1c499'
down_revision: Union[str, None] = '100c08b1fc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactentrymodel', schema=None) as batch_op:
        batch_op.alter_column('middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
